apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmiapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: bmiapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: bmiapp
        image: swancrawford/bmiapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: bmiapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: bmiapp
